spring:
    datasource:
        url: jdbc:h2:mem:dev
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2
    liquibase:
        change-log: classpath:database/changelog.yml
springdoc:
    api-docs:
        path: /api/doc
    swagger-ui:
        path: /api/doc-ui