CREATE TABLE holidays
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(500) NOT NULL,
    day_value   SMALLINT     NOT NULL,
    month_value SMALLINT     NOT NULL
);

INSERT INTO holidays(name, day_value, month_value)
VALUES ('Dzień Mleka', 1, 6),
       ('Święto Bułki', 1, 6),
       ('Dzień bez Alkoholu', 1, 6),
       ('Dzień bez Krawata', 2, 6),
       ('Dzień Macochy', 2, 6),
       ('Dzień Chemika', 2, 6),
       ('Dzień dobrej Oceny', 3, 6),
       ('Dzień Savoir-Vivre', 3, 6),
       ('Światowy Dzień Roweru', 3, 6),
       ('Dzień Drukarza', 4, 6),
       ('Dzień Demokracji', 4, 6),
       ('Dzień Ochrony Środowiska', 5, 6),
       ('Światowy Dzień Środowiska', 5, 6),
       ('Dzień Slayera', 6, 6),
       ('Dzień Seksu', 7, 6),
       ('Dzień Informatyka', 8, 6),
       ('Dzień Przyjaciela', 9, 6),
       ('Międzynarodowy Dzień Elektryka', 10, 6),
       ('Międzynarodowy Dzień Rysia', 11, 6),
       ('Dzień Stylisty Paznokci', 12, 6),
       ('Dzień Dobrych Rad', 13, 6),
       ('Międzynarodowy Dzień Kąpieli', 14, 6),
       ('Dzień Wiatru', 15, 6),
       ('Międzynarodowy Dzień Pomocy Dzieciom Afrykańskim', 16, 6),
       ('Dzień Walki z Pustynnieniem i Suszami', 17, 6),
       ('Dzień Ewakuacji', 18, 6),
       ('Teksański Dzień Emancypacji', 19, 6),
       ('Światowy Dzień Uchodźcy', 20, 6),
       ('Święto Muzyki', 21, 6),
       ('Światowy Dzień Grubasa', 22, 6),
       ('Dzień Służby Publicznej', 23, 6),
       ('Dzień Przytulania', 24, 6),
       ('Dzień Stocznicowa', 25, 6),
       ('Międzynarodowy Dzień Solidarności z Osobami Uzależnionymi od Narkotyków', 26, 6),
       ('Międzynarodowy Dzień Mikro-, Małych i Średnich Przedsiębiorstw', 27, 6),
       ('Narodowy Dzień Pamięci Poznańskiego Czerwca 1956', 28, 6),
       ('Dzień Ratownika WOPR', 29, 6),
       ('Dzień Asteroid', 30, 6);
